server:
  port: 8081
spring:
  application:
    name: shows-service
  datasource:
    url: ${SHOWS_DB_URL:jdbc:postgresql://localhost:5432/shows-db}
    username: ${SHOWS_DB_USER:cinema}
    password: ${SHOWS_DB_PASSWORD:cinema}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

